---
title: "Isolates Map"
author: "Finn Lobnow"
date: format(Sys.time(), "%d %B, %Y")
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, include = TRUE, echo = F, message=F}
library(tidyverse)
library(knitr)
library(ggpubr)
library(readr)
library(tibble)
library(leaflet)
library(htmltools)
library(ggVennDiagram)
library(fishualize)
```

# THE ISOLATES

```{r, isolates, echo=FALSE, message = F}
#isolates_used <- read.csv("https://raw.githubusercontent.com/tlobnow/Crypto/main/Genome_Analysis/markdown/used_Isolates_new.csv")
isolates_used <- read.csv("https://raw.githubusercontent.com/tlobnow/gap/main/resources/isolate_details.csv")

kable(isolates_used)

SOTA <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/SOTA_Data_Product.csv")  %>% filter(!is.na(Latitude), !is.na(Longitude), !is.na(HI), !Mouse_ID %in% c("SK_2697", "SK_3173", "SK_905"))

Crypto_Detection <- read.csv("https://raw.githubusercontent.com/derele/Mouse_Eimeria_Field/master/data_products/Crypto_Detection.csv")  %>% filter(#Year == 2021, 
  ILWE_Crypto_Ct > 0, !is.na(Latitude), !is.na(Longitude))

Czech <- read.csv("https://raw.githubusercontent.com/tlobnow/Cryptosporidium-BSc/Main-Branch/Analysis/Clade_Memberships.csv")


# color palette for HI
r <- c(0,    64, 128, 179, 217, 255)
g <- c(0,    12,  25,  25,  12,   0)
b <- c(255, 249, 243, 191,  95,   0)

beach <- function (n, name = c("beach.colors")) 
  {
    beach.colors = rgb(r,g,b,maxColorValue = 255)
    name = match.arg(name)
    orig = eval(parse(text = name))
    rgb = t(col2rgb(orig))
    temp = matrix(NA, ncol = 3, nrow = n)
    x = seq(0, 1, , length(orig))
    xg = seq(0, 1, , n)
    for (k in 1:3) {
      hold = spline(x, rgb[, k], n = n)$y
      hold[hold < 0] = 0
      hold[hold > 255] = 255
      temp[, k] = round(hold)
    }
    palette = rgb(temp[, 1], temp[, 2], temp[, 3], maxColorValue = 255)
    palette
}

data_col_HI_Level = colorFactor(beach(6), SOTA$HI_Level)
data_col_HI       = colorFactor(beach(6), SOTA$HI)

```

## Samples with Illumina Sequencing Results

``` {r Illumina-HMHZ, echo = F, warning = F, message = F}

Illumina <- Crypto_Detection %>%
  mutate(illumina = Mouse_ID %in% c("AA_0900", "AA_0866", "AA_0942")) %>%
  filter(illumina == T)

map <- Crypto_Detection %>% leaflet() %>% addProviderTiles("CartoDB") %>% setView(lat = 52.520007, lng =13.404954, zoom = 6)
map1 <- map %>%
  addPolylines(lat = c(55.0000, 53.6000, 53.51885, 52.8875  , 52.6053, 51.8978, 45.0000), 
               lng = c(10.0000, 11.4563, 12.4464,13.8119 , 13.8756, 13.8103, 10.0000), 
               color = "purple", 
               weight = 55, 
               opacity = 0.1) %>%
  addCircleMarkers(data = SOTA,
                   col = ~data_col_HI(HI),
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  "<b>Year:<b>",    as.character(Year),"<br>",
                                  "<b>Ct Mean:<b>",      as.character(round(ILWE_Crypto_Ct, digits = 2)),"<br>",
                                  "<b>Oocyst Prediction:<b>", as.character(Oocyst_Predict_Crypto), "<br>",
                                  "<b>Sex:<b>", Sex, "<br>",
                                  sep=" "),
                   opacity = 1,
                   radius = 3,
                   group = "Samples (total)") %>%
  addCircleMarkers(data = Illumina,
                   color = 'black',
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 6,
                   group = 'black') %>%
  addCircleMarkers(data = Illumina,
                   color = 'orange',
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 4,
                   group = 'Illumina') %>%
  addCircleMarkers(data = Illumina,
                   color = 'orange',
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 3,
                   group = 'Illumina2') %>%
  
  addLegend("bottomleft", 
            pal = data_col_HI_Level, 
            title = "Hybrid Index",
            values = SOTA$HI_Level, 
            group = c('HI = 0.00', 'HI < 0.25', 'HI < 0.50', 'HI < 0.75', 'HI < 1.00', 'HI = 1.00'),
            opacity = 1) %>%
  addLayersControl(overlayGroups = c('Illumina', 'Illumina2', "Samples (total)"),
                   options = layersControlOptions(collapsed = T))
map1
```

## Spatial Distribution of Samples

``` {r, isolates-map, echo = F, message = F, warning = F}
tyzzeri <- isolates_used %>% filter(Species == "C.tyzzeri")
parvum  <- isolates_used %>% filter(Species == "C.parvum")
hominis <- isolates_used %>% filter(Species == "C.hominis")
meleagridis <- isolates_used %>% filter(Species == "C.meleagridis")


mus <- isolates_used %>% filter(Host == "Mus")
cattle <- isolates_used %>% filter(Host == "Cattle")
human <- isolates_used %>% filter(Host == "Human")
map <- isolates_used %>% leaflet() %>% addProviderTiles("CartoDB") %>% 
  setView(lat = 28.826860466881197, lng =3.19112480333911, zoom = 1)
map1 <- map %>%
  #addPolylines(lat = c(55.0000, 53.6000, 53.51885, 52.8875  , 52.6053, 51.8978, 45.0000), 
  #             lng = c(10.0000, 11.4563, 12.4464,13.8119 , 13.8756, 13.8103, 10.0000), 
  #             color = "purple", 
  #             weight = 10, 
  #             opacity = 0.4) %>%
  
  addCircleMarkers(data = hominis,
                   col = "#73be73",
                   opacity = 1,
                   label = ~htmlEscape(Abbr_Reg),
                   popup = ~paste("<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude)),
                   radius = 3,
                   group = "C.hominis") %>%
  addCircleMarkers(data = parvum,
                   col = "blue",
                   opacity = 1,
                   label = ~htmlEscape(Abbr_Reg),
                   popup = ~paste("<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude)),
                   radius = 3,
                   group = "C.parvum") %>%
  addCircleMarkers(data = meleagridis,
                   col = "red",
                   opacity = 1,
                   label = ~htmlEscape(Abbr_Reg),
                   popup = ~paste("<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude)),
                   radius = 3,
                   group = "C.meleagridis") %>%
  addCircleMarkers(data = tyzzeri,
                   col = "black",
                   opacity = 1,
                   label = ~htmlEscape(Abbr_Reg),
                   popup = ~paste("<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude)),
                   radius = 4,
                   group = "C.tyzzeri background") %>%
  addCircleMarkers(data = tyzzeri,
                   col = "orange",
                   opacity = 1,
                   label = ~htmlEscape(Abbr_Reg),
                   popup = ~paste("<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude)),
                   radius = 3,
                   group = "C.tyzzeri") %>%
  addLegend("bottomright", 
            colors = c('orange', 'blue', '#73be73', "red"),
            labels = c('C.tyzzeri',
                       'C.parvum',
                       'C.hominis',
                       "C.meleagridis"),
            title = 'Species',
            opacity = 1) %>%
  addLayersControl(overlayGroups = c('C.tyzzeri background', 'Background', 'C.tyzzeri', 'C.parvum', 'C.hominis', "C.meleagridis"), 
                   options = layersControlOptions(collapsed = T))
map1
```


## Samples with CTA (Leucine) deletion in GP60

``` {r GP60-HMHZ, echo = F, warning = F, message = F}

Illumina <- Crypto_Detection %>%
  mutate(illumina = Mouse_ID %in% c("AA_0900", "AA_0866", "AA_0942")) %>%
  filter(illumina == T)

SNP <- full_join(Czech, Crypto_Detection) %>% dplyr::select("Mouse_ID", "Longitude", "Latitude", "HI")

Sequenced <- SOTA %>% mutate(seq = Mouse_ID %in% c("AA_0144", "AA_0325", "AA_0689", "AA_0209", "AA_0282", "AA_0793", "AA_0667", 
                                                   "AA_0805", "AA_0900", "AA_0523", "AA_0534", "AA_0537", "AA_0545", "AA_0546", 
                                                   "AA_0553", "AA_0554", "AA_0555", "AA_0557", "AA_0559", "AA_0571", "AA_0578", 
                                                   "AA_0580", "AA_0589", "AA_0601", "AA_0660", "AA_0666", "AA_0585", "AA_0667", 
                                                   "AA_0669", "AA_0679", "AA_0866", "AA_0942")) %>% filter(seq == T)

SNP <- SNP %>%
  mutate(LeucineDel = Mouse_ID %in% c("CR_2208",
                                     "CR_2206",
                                     "CR_2084",
                                     "CR_2127",
                                     "CR_2126",
                                     "CR_2085",
                                     "CR_2128",
                                     "CR_2149",
                                     "CR_2125",
                                     "AA_0866",
                                     "AA_0523",
                                     "AA_0282")) %>% filter(LeucineDel == T) %>% unique()



map <- Crypto_Detection %>% leaflet() %>% addProviderTiles("CartoDB") %>% setView(lat = 52.520007, lng =13.404954, zoom = 7)
map1 <- map %>%
  addPolylines(lat = c(55.0000, 53.6000, 53.51885, 52.8875  , 52.6053, 51.8978, 45.0000), 
               lng = c(10.0000, 11.4563, 12.4464,13.8119 , 13.8756, 13.8103, 10.0000), 
               color = "purple", 
               weight = 55, 
               opacity = 0.1) %>%
  # addCircleMarkers(data = SOTA,
  #                  col = ~data_col_HI(HI),
  #                  label = ~htmlEscape(Mouse_ID),
  #                  popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
  #                                 "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
  #                                 "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
  #                                 "<b>Year:<b>",    as.character(Year),"<br>",
  #                                 "<b>Ct Mean:<b>",      as.character(round(ILWE_Crypto_Ct, digits = 2)),"<br>",
  #                                 "<b>Oocyst Prediction:<b>", as.character(Oocyst_Predict_Crypto), "<br>",
  #                                 "<b>Sex:<b>", Sex, "<br>",
  #                                 sep=" "),
  #                  opacity = 1,
  #                  radius = 3,
  #                  group = "Samples (total)") %>%
  addCircleMarkers(data = Sequenced,
                   color = ~data_col_HI(HI),
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 3,
                   group = 'sequenced') %>%
  addCircleMarkers(data = SNP,
                   color = 'black',
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 6,
                   group = 'black') %>%
  addCircleMarkers(data = SNP,
                   color = 'orange',
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 4,
                   group = 'SNP') %>%
  addCircleMarkers(data = SNP,
                   color = 'orange',
                   label = ~htmlEscape(Mouse_ID),
                   popup = ~paste("<b>Mouse_ID:<b>",as.character(Mouse_ID), "<br>",
                                  "<b>Location:<b>", as.character(Latitude), "<b>,<b>", as.character(Longitude), "<br>",
                                  "<b>HI:<b>",      as.character(round(HI, digits = 2)), "<br>",
                                  sep=" "),
                   opacity = 5,
                   radius = 3,
                   group = 'SNP2') %>%
  addLegend("bottomleft", 
            pal = data_col_HI_Level, 
            title = "Hybrid Index",
            values = SOTA$HI_Level, 
            group = c('HI = 0.00', 'HI < 0.25', 'HI < 0.50', 'HI < 0.75', 'HI < 1.00', 'HI = 1.00'),
            opacity = 1) %>%
  addLayersControl(overlayGroups = c('SNP', 'SNP2',"sequenced"#, "Samples (total)"
                                     ),
                   options = layersControlOptions(collapsed = T))
map1
```